# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ed5bc2778f00cee833294e781875df38467a9c9ecc12295151706f17f748e1a1a340d0cabccad3c8b5344f27162cc7ad6bbec802ee811b539232185f248f36e
  facebook_app_id: <%= ENV["BIBLIO_ID"] %>
  facebook_app_secret: <%= ENV["BIBLIO_PW"] %>

test:
  secret_key_base: da8cf0936221bbdef7b1f44ee4d9f835f3820017babed84c29fbe55f2bf31cec412c0616edc1267c9ef80fa5496c648e7e176f609e5676a55cbd22ec69a0210c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
